version: 2

builds:
  - ldflags: "-s -w"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

changelog:
  use: github-native
